configs:
  services:
    - service_name: online-bb-member
      machine:
        machine_user: mmpprd
        machine_password: i29PmmpImK
        params:
          - -Dspring.profiles.action=prod
      git:
        jar_path: brand-member-api/target
        git_url: git@120.78.168.136:watsons/mmp-brand-member.git
        git_branch: develop
        git_user: wujunjie@pconline.com.cn
        git_password: wujunjie
      targets:
        - ip: 10.44.0.177
          port: 8080
        - ip: 10.44.0.178
          port: 8081


