configs:
  services:
    - service_name: online-bb-member
      machine:
        deploy_path: //todo 晚点再弄
        machine_user: mmpprd
        machine_password: i29PmmpImK
        params:
          - -Dspring.profiles.action=prod
      git:
        jar_path: brand-member-api/target
        git_url: git@120.78.168.136:watsons/mmp-brand-member.git
        git_branch: develop
        git_user: wujunjie@pconline.com.cn
        git_password: wujunjie
      targets:
        - ip: 10.82.34.134
          port: 8000
          deploy_path: //todo 晚点再弄
          machine_user: mmpprd
          machine_password: i29PmmpImK
        - ip: 10.82.34.135
          port: 9000


